title: James Kay
theme: jekyll-theme-minima


SUMMARY
 
Senior IT Consultant transitioning into AI engineering, with a focus on AWS Bedrock, Python, and Vector Store
search technologies. Currently building hands-on projects using LangChain, Pinecone, and ChromaDB to design intelligent,
cloud-native solutions powered by large language models. Eager to join a collaborative team working on real-world AI-driven
related applications.
PROFESSIONAL EXPERIENCE 
INFOSYS (IT Consulting) TOKYO, JAPAN
Senior Consultant January 2023 – Present
Jan 2025 – Present (Infosys AI/ML Team Initiative)
● Engaged in Infosys’s internal AI/ML initiative for the Japan business unit, focused on hands-on upskilling and exploration of
generative AI use cases, including large language models (LLMs), RAG pipelines, and intelligent automation.
● Contributed to pre-sales preparation and early-stage solution design, assisting in the development of proof-of-concept proposals
using tools such as LangChain, OpenAI, AWS Bedrock, Pinecone, and ChromaDB. Collaborated with a cross-functional
team on prompt engineering and vector database strategies to support enterprise AI adoption.
● While initial efforts have been exploratory and budget-dependent, this initiative has solidified my technical direction and
reinforced my desire to join a team actively building and deploying AI-powered solutions in production environments.
Project: Google (Jan 2023 – Jan 2025)
● Successfully Resolved 300+ complex technical cases for Google Enterprise clients, focusing on infrastructure services including
Load Balancing, VPC Service Controls, GKE, IAM policies, and Workload Identity Federation
● Delivered expert guidance on GCP security architecture and IAM Federation, helping clients reduce risk, improve operational
efficiency, and deploy secure, scalable systems
● Led first-touch resolution strategies, improving case turnaround time and increasing customer satisfaction
● Mentored junior engineers through case-sharing, documentation, and technical coaching, enhancing team collaboration and
service delivery
● Implemented production-level improvements across customer cloud environments, including Compute Engine, Organizational
Policies, and IAM role enforcement
● Ensured compliance and performance optimization by troubleshooting real-time infrastructure issues in large-scale,
mission-critical deployments
Transition Focus:
Since early 2024, have been actively skilling up in AWS cloud services for AI, Python development, and AI/LLM-based solution
architecture using tools such as LangChain, Bedrock, Pinecone, and ChromaDB.
__________________________________________________________________________________________________________________________________________________________________________________
Professional Development Sabbatical: Career Transition to Cloud Technologies July 2022 – December 2022
July 2022 – December 2022
Took a planned sabbatical to strategically shift back into hands-on technical work after years in infrastructure and support roles. Rather
than picking up surface-level skills while juggling a demanding full-time job, I made a short-term investment to go deep and reset my
technical foundation for long-term career growth.
During this time, I completed over 1,000 hours of intensive study across AWS, GCP, Azure, and Python programming, earning multiple
cloud certifications and completing full-stack development training. This dedicated focus enabled me to return to the workforce with a
renewed direction, stronger cloud-native skill set, and a clear goal of contributing to AI-powered, scalable cloud solutions.
Jones Day (Law Firm) TOKYO, JAPAN
TSS Manager November 2019 – June 2022
● Led the successful relocation of the Tokyo office and on-premises data center, overseeing infrastructure setup, hardware
deployment, and continuity planning in coordination with global IT teams
● Directed the firm’s transition to remote work during the COVID-19 pandemic by implementing secure VPN access and remote
desktop environments, enabling uninterrupted operations for legal professionals
● Managed the rollout of Windows 10 (20H2) across all endpoints, improving system security, stability, and user productivity
● Supported network improvements through coordination of VLAN segmentation and post-relocation connectivity testing
● Standardized endpoint configurations and IT operations in alignment with global compliance requirements and firm-wide
infrastructure practices
__________________________________________________________________________________________________
Hogan Lovells (Law Firm) TOKYO / JAPAN
IT Site Manager September 2018 – October 2019
Provided end-to-end IT support and infrastructure oversight for the Tokyo office, with extended coverage for Hong Kong and Singapore.
Supported hybrid environments using on-prem systems and cloud-based tools, and played a key role in coordinating office relocations and
infrastructure improvements.
Optimized daily operations by managing ServiceNOW workflows and VMware infrastructure, ensuring system reliability and timely issue
resolution across the region. Maintained high service quality in a fast-paced, global legal environment, while collaborating closely with firm
leadership and IT counterparts across APAC.
Transition Note: Joined Jones Day following an invitation from a senior partner I supported at Hogan Lovells, who brought me on board
to continue providing IT leadership in a new office environment.
____________________________________________________________________________________________________________
UBER TOKYO / JAPAN
Senior IT Service Support Manager June 2017 – August 2018
Provided end-to-end technical support and infrastructure operations for a fast-paced startup environment. Delivered improvements across
user support workflows, data center maintenance, and endpoint systems, while playing a key role in major infrastructure projects.
● Office & Data Center Relocation: Successfully led the relocation of the company’s office and data center, including planning,
hardware reinstallation, and post-move network stabilization
● Infrastructure Enhancements: Identified and implemented improvements to workstation configurations, backup procedures,
and user onboarding processes to reduce recurring incidents
● Technical Support & Operations: Delivered Tier 1–3 user support across desktop, network, and server environments;
performed data center maintenance and systems monitoring
● Ticket Management: Managed IT service queue by triaging, prioritizing, assigning, and escalating tickets to ensure SLA
compliance and efficient resolution
● Cross-Functional Collaboration: Worked closely with developers and operations teams to support deployment environments,
asset provisioning, and local IT compliance.
Note: Proactively began exploring new opportunities after the company announced its planned exit from Southeast Asia
operations.
___________________________________________________________________________________________________________
Fortress Investments TOKYO / JAPAN
Regional IT Support Manager May 2015 – May 2017
As a cross-border Technical Support Lead, I provided Level 2 and Level 3 support for global real estate operations, delivering
enterprise-grade solutions across international offices. Leveraged advanced cloud technologies to resolve complex infrastructure issues,
enhance system performance, and drive operational scalability. Key accomplishments include:
● Led IT infrastructure planning and execution for a ¥30M office expansion, including network design, endpoint deployment,
vendor coordination, and zero-downtime rollout.
● Deployed AWS S3 solutions integrated with AWS Storage Gateway and IAM policies to enable secure hybrid storage and backup
workflows.
● Designed and piloted serverless architectures using AWS Lambda and API Gateway to support scalable, cost-efficient property
management processes and internal tools.
___________________________________________________________________________________________________________
Eastspring Investments TOKYO / JAPAN
Head of Infrastructure (Consultant) November 2012 – October 2014
Managed enterprise IT infrastructure across 40 servers and two data centers, supporting financial systems in a regulated, high-availability
environment. Combined hands-on engineering with strategic planning, vendor coordination, and infrastructure modernization.
● Led redesign of Tokyo data center’s Layer 2/3 network core, improving performance, redundancy, and scalability
● Re-architected Active Directory and Group Policy; implemented profile management, login scripting, and access controls
● Deployed Remote Desktop Services (RDS) cluster with load balancing for 100+ thin client users
● Designed and implemented SAN-based backup and disaster recovery architecture using Arcserve and Backup Exec;
established BCP replication to secondary Kyoto data center
● Performed server risk assessments and failover planning for a 40-server Windows blade environment
● Managed third-party vendors for hardware, licensing, and infrastructure upgrades; ensured compliance and SLA performance
● Built the company’s first internal Helpdesk ticketing system and formalized documentation standards for all critical IT systems,
processes, and dependencies
● Provided Level 3 support for business-critical financial apps including Bloomberg Terminal, FundWeb, EDINET, and Lotus
Notes
__________________________________________________________________________________________________
British Telecom TOKYO / JAPAN
Technical Designer November 2008 – February 2011
Provided full-cycle technical consultation and service delivery for global financial institutions across Tokyo, spanning pre-sales engagement,
solution design, and post-sales support. Acted as a key interface between clients and the technical design team to ensure successful solution
delivery within a highly regulated financial environment.
● Delivered pre-sales technical support for new client opportunities, including cost analysis, network design proposals, and
solution architecture tailored to institutional finance needs
● Collaborated closely with the technical design team, transitioning from client-facing roles to contribute to infrastructure
planning, documentation, and custom solution development
● Managed post-sales service delivery, overseeing onboarding, incident response, and change management procedures in
alignment with ITIL best practices
● Served as primary contact for assigned foreign financial institutions, providing ongoing support across network
performance, billing reconciliation, and documentation updates
● Acted as a technical liaison between global support teams and Tokyo-based clients, ensuring alignment on service expectations
and accelerating issue resolution for time-sensitive environments
● Developed and maintained detailed documentation for customer environments, including service portfolios, utilization reporting,
and network topology overviews
____________________________________________________________________________________________________________
Mckinsey&Company TOKYO / JAPAN
IT Data Center Consultant October 2007 – October 2008
Redesigned the company’s on-premises data center while providing Tier 1–2 helpdesk support to a 200-user environment.
● Led full data center architecture redesign, including rack layout, power distribution, cable management, and air cooling
compliance in line with environmental and operational standards
● Implemented infrastructure standards for cooling airflow optimization, power load balancing, and heat dissipation per rack;
ensured compliance with internal BCP and facility safety protocols
● Conducted comprehensive technical audit across servers and infra assets: OS patching, power redundancy checks, RAID
integrity, user access audits, and warranty validation
● Managed vendor relationships and RFP processes, including procurement planning, contract negotiation, and change
management
● Enforced physical security and stability measures such as earthquake plating, secured rack installations, and documented data
center procedures
● Delivered daily support for Windows OS, MS Office, VoIP systems, Lotus Notes, and file/print servers
● Maintained detailed inventory tracking for all circuits, voice/data lines, servers, and infrastructure hardware
____________________________________________________________________________________________________________
HMV JAPAN TOKYO / JAPAN
Network and PC Manager July 2001 – September 2007
Led the end-to-end design, implementation, and administration of IT infrastructure across Japan, including the national WAN, store
networks, and corporate headquarters in Roppongi. Acted as both technical lead and infrastructure manager, overseeing day-to-day
operations while driving strategic initiatives and modernization efforts.
● Network & Systems Architecture: Designed and maintained the company’s WAN, implemented new Cisco 3600 series routers,
VPN concentrators, and administered Cisco PIX firewalls to support secure, scalable connectivity across 40+ locations
● Server Infrastructure Leadership: Led server room redesign including rack infrastructure and server upgrades; implemented
Active Directory, Exchange 2000, and centralized backup solutions to enhance security, performance, and maintainability
● Retail IT Rollouts: Directed national workstation deployments, public kiosks, and full IT support for new store openings and
retail refits
● Store Support & Operations: Provided Level 3 support for all stores in Japan; managed the successful migration of 40 stores
to ADSL
● Team & Vendor Management: Supervised a team of 2 engineers and served as primary liaison between the Japan office and the
global Director of IT; coordinated with external vendors on infrastructure projects and support contracts
● Security & Compliance: Authored security audit documentation, led remediation efforts, and implemented improved policy
controls across endpoints and infrastructure
● Strategic Contributions: Produced infrastructure proposals and technical documentation for executive stakeholders; helped
define IT standards and operations strategy for the Japan region
____________________________________________________________________________________________________________
Devise Associates New York / United States
Onsite Field Engineer September 1996 – September April 2001
Provided on-site infrastructure and end-user support for Fortune 500 clients across finance, healthcare, energy, and legal sectors.
● Performed server staging, imaging, and configuration for enterprise rollouts and hardware refresh projects
● Delivered advanced desktop and endpoint troubleshooting, including OS, application, and peripheral support
● Handled structured cabling, patch panel management, and physical rack assembly in high-density data center and office
environments
● Ensured hardware standards and documentation compliance across multi-sector client environments, adapting to strict SLAs and
business-specific operational needs
● Supported infrastructure continuity by collaborating with internal teams and vendors during scheduled installs, upgrades, and
maintenance windows
____________________________________________________________________________________________________________
Four Seasons Hotel New York / United States
Reception/Front Desk February 1993 – November 1995
Delivered high-level front desk service to guests in a luxury hospitality environment. Handled reservations, check-ins, and guest inquiries
with professionalism and discretion.
● Built early experience in customer service, attention to detail, and working under pressure — foundational skills that later
supported success in client-facing technical roles
___________________________________________________________________________________________________________
 Current Visa Status: 5yr. Spousal Visa (Married to Japanese National) Authorized to work in Japan.
 Availability: Negotiable
